name: channel-2

on:
  # schedule:
  #   - cron: '20,50 * * * *'
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  channel-2:
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repo and run code
      env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      run: |
          git clone https://x-access-token:${PAT_GITHUB}@github.com/tatamu-fold/meet-greet.git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Specify the Python version you need
    - name: Download FFmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg 
        ffmpeg -version

    - name: Run Python script
      run: |
        cd meet-greet
        pip install requests
        python miiguri-video.py
      env:
        channel_id: "-1001409848887"
        bot_token: ${{ secrets.bot_token }}
        m3u8_url: ${{ secrets.m3u8_url }}
